# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c3782d803a068e3d73bb019cebfef5c5"
name = "Collection Manager"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete", "collections/delete"]
uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_content,read_content,read_publications,write_publications,read_metaobjects"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
